name       : superlu
version    : 6.0.0
release    : 6
source     :
    - https://github.com/xiaoyeli/superlu/archive/refs/tags/v6.0.0.tar.gz : 5c199eac2dc57092c337cfea7e422053e8f8229f24e029825b0950edd1d17e8e
license    : BSD-3-Clause
component  : programming.library
homepage   : https://portal.nersc.gov/project/sparse/superlu/
summary    : SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations
description: |
    SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations. The library is written in C and is callable from either C or Fortran program. It supports both real and complex datatypes, both single and double precision, and 64-bit integer indexing.
builddeps  :
    - pkgconfig(openblas)
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_XSDK_DEFAULTS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
