name       : superlu
version    : 5.2.1
release    : 1
source     :
    - https://github.com/xiaoyeli/superlu/archive/v5.2.1.tar.gz : 77582501dedef295eb74e4dc9433e2816d2d8be211eae307379c13d93c65bc71
license    : BSD-3-Clause
component  : programming.library
summary    : SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations
description: |
    SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations. The library is written in C and is callable from either C or Fortran program. It uses MPI, OpenMP and CUDA to support various forms of parallelism. It supports both real and complex datatypes, both single and double precision, and 64-bit integer indexing
builddeps  :
    - pkgconfig(openblas)
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=1 -DUSE_XSDK_DEFAULTS=1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test